### PR TITLE
Updated for new getOrganization function

### PR DESCRIPTION
**Pull request by ryantsullivan**
OK, trying this again. I think I have gotten this to work now.

### CODE REVIEW

**Comment by ryantsullivan** [comment]
This is just mean to be a simple function to grab general information and stats on an organization. Figured it was an easy one to start with that I already use to keep an eye on user engagement and keep track of how many auditable responses we have used in my organization.

**Comment by JasperHG90** [comment]
Great! Couple of things I forgot to mention in the thread (apologies).

1. Add changes to the [news.md](https://github.com/JasperHG90/qualtRics/blob/master/news.md) branch
2. The build seems to be failing 
3. It's good to write unit tests for functions. Have a look [here](https://github.com/JasperHG90/qualtRics/tree/master/tests/testthat). I'll write a unit test for your new function (it's a bit particular because of the 'httptest' package), but in the future please add.

Thanks!

**Comment by ryantsullivan** [comment]
1. I will get the news.md updated.

2. I see something about namespace dependency purrr not required in the travis-ci error. However, I don't know if I understand that error since I am using a purrr function; so I would think it should be in the namespace. 

3. Cool, thanks for the heads up. I saw those but I have never written unit tests before. It seems to make sense but might be a trial and error kind of thing. 

Should PRs go to the master branch or the development branch?

**Comment by JasperHG90** [comment]
Given that there are some issues to be figured out (+ some tests to be written) this should go into the development branch! Thanks

**Comment by JasperHG90** [comment]
@ryantsullivan : I'm closing this. Could you send merge your master branch into your development branch and send a pull request to my development branch? Thanks!

**Comment by ryantsullivan** [comment]
@JasperHG90 Sorry. I got a bit slammed at work but I will do this as soon as I can. Will you be at Qualtrics X4 by any chance?

**Pull request closed without merging**
