### PR TITLE
Add question label and force response output in getSurveyQuestions()

### PR DESCRIPTION
**Pull request by phoebewong**
I added question label in response to issue #35 in the output of `getSurveyQuestions()`. 

I also added force response (logical) in the output because I personally found it helpful as I sometimes use that to check if all questions have force response validated before publishing the survey. Let me know what do you think. Thanks!

### CODE REVIEW

**Comment by phoebewong** [comment]
Working on fixing the error

**Comment by JasperHG90** [comment]
Thanks!

**Comment by phoebewong** [comment]
Hi @JasperHG90, I actually meant that I was working on fixing the error, since some tests still failed and the coverage decreased. The error was not fixed, but it is now fixed now. Should I make a new merge request now? Thanks!

**Comment by JasperHG90** [comment]
Ah! I shouldn’t do these things late at night ... doh! Yes please do!

**Comment by phoebewong** [comment]
No problem! I submitted a new PR, although it looks like it still failed the test.. Is it just because I haven't written a test for it?

**Pull request merged**
