### PR TITLE
Update qlabel to handle NA correctly for surveys without question labels

### PR DESCRIPTION
**Pull request by phoebewong**

### CODE REVIEW

**Comment by JasperHG90** [comment]
Hi Phoebe,

Thanks! I'll review the tests on Friday so that this works. I needed to update the CRAN version anyway.

Best,

J.

**Comment by phoebewong** [comment]
Thanks! Let me know if there's anything I should change or note for future references.

**Comment by JasperHG90** [comment]
Hi Phoebe,

Don't worry about the failed tests; it just says that the code coverage decreased by a marginal percentage!

Thanks for this.

J.

**Comment by phoebewong** [comment]
Sounds good, thank you!

**Pull request merged**
