### PR TITLE
Fix a bug where one line too much is skipped in readSurvey.R.

### PR DESCRIPTION
**Pull request by EruIluvatar**
Hi Jasper,
Stefan and Adrian here.

We noticed that always the first row of data is missing when using `readSurvey`.
This PR reverts a change (skip = 2 -> 3) that you probably introduced when adapting our original code to the package.

Also the `importids` are never used after creating it. Which is why we remove it.

Thanks for considering this PR!

### CODE REVIEW

**Comment by EruIluvatar** [comment]
I just realized that qualtrics changed their export formats since the beginning of the year.
We have worked with the now-called "legacy" format, it seems you adapted it to the now "standard" format when integrating it?

My suggestion is that we introduce another paramater `legacy` which defaults to `FALSE`.
When set to `TRUE`, we want to only skip 2 lines.

How do you feel about that?
Needless to say that this PR is not ready for merge from my side. 

---
Attached: sample of standard and legacy format. Feel free to use them directly in the test.
[readSurveyTest_export-samples.zip](https://github.com/JasperHG90/qualtRics/files/1155029/readSurveyTest_export-samples.zip)

**Comment by EruIluvatar** [comment]
Sorry for the amount of changes, most lines are because of refactoring tabstop 4 to 2.
Makes the diffs a bit messy...

**Comment by JasperHG90** [comment]
Hi Adrian, Stefan,

Thanks for your comments! 

One question: is it absolutely necessary to use UTF encoding? Could create problems on Windows machines. See issues #36, #41 and #38.

J

**Comment by EruIluvatar** [comment]
Thanks for your feedback Jasper.

Just to make clear, the UTF-8-BOM encoding is only enabled if we want to read a legacy csv export.

The problem is that the [sample file using the legacy export](https://raw.githubusercontent.com/EruIluvatar/qualtRics/b8d9c7ec7621dea34281113aa3c6bb59e84e390e/tests/testthat/files/sample_legacy.csv) always has UTF-8 with byte order mark encoding as obtained from qualtrics.com.
The byte order mark is another byte at the start of the file, causing a corrupted first entry (V1 turns into something like ï»¿V1).
[See more at stackoverflow](https://stackoverflow.com/questions/3255993/how-do-i-remove-%c3%af-from-the-beginning-of-a-file#3256014). This was the reason we put "UTF-8-BOM" in there in the first place, because an empty parameter, "latin1" or "UTF-8" would corrupt our first column name.

Now we observed that while the legacy exports have the UTF-8 with BOM, the new (standard) exports have regular UTF-8 encoding _without_ BOM. That's why the encoding is only set when using readSurvey with `legacyFormat = TRUE`.

For what it's worth we tested this on Windows 10 and Mac OS.

**Comment by JasperHG90** [comment]
Got it! Thanks for the explanation.

**Pull request merged**
